In [1]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.rand(5,2),index=range(0,10,2),columns=['sensor_00', 'time'])
df2 = pd.DataFrame([1,2,3,4,5],index=range(0,10,2), columns=['A'])
df

sensor_00      time
0   0.369416  0.282689
2   0.948058  0.642106
4   0.822310  0.821470
6   0.755674  0.237346
8   0.919836  0.995079

In [6]:
for a in df:
    print(a)  

sensor_00
time


In [14]:
dum2 = 3
def some_func(some_input):
    print(dum2)
    return dum2


In [10]:
column_list = df.columns.values.tolist()
sensor_list = [s for s in column_list if 'sensor' in s]
sensor_list

['sensor_00']

In [8]:
gb = df.groupby(pd.cut( df['A'], np.arange(0, 1.5, 0.5) ))['B'].mean()
gb
gb.values

array([0.17107832, 0.35697301])

In [12]:
int(5/3)

1

In [4]:
liste = df2.iloc[:,0].rolling(window=11, center=True, min_periods=1).mean()
df2['D'] = df2['A']/liste
print(liste)
print(df2)

0    3.0
2    3.0
4    3.0
6    3.0
8    3.0
Name: A, dtype: float64
   A         D
0  1  0.333333
2  2  0.666667
4  3  1.000000
6  4  1.333333
8  5  1.666667


In [3]:
df_new = df.iloc[0:0]
print(df.loc[:,'A'].values)
df_new.loc[:,'A'] = df.loc[:,'A'].values.reshape(-1,1)
df_new

[0.82283406 0.53456868 0.38746096 0.70988506 0.30258433]


Exception: Data must be 1-dimensional

In [5]:
a = df['A']
a - 5


0   -4.478273
2   -4.317784
4   -4.098333
6   -4.620135
8   -4.765726
Name: A, dtype: float64

In [13]:
a[:,0].shape

(5,)

In [6]:
df1 = pd.DataFrame({'User': ['user1', 'user1', 'user2', 'user3', 'user2', 'user3'],
                 'B': ['B', 'B1', 'B2', 'B3','B4','B5'],
                 'C': ['C', 'C1', 'C2', 'C3','C4','C5'],
                 'D': ['D', 'D1', 'D2', 'D3','D4','D5'],
                 'E': ['E', 'E1', 'E2', 'E3','E4','E5']})
df1

User   B   C   D   E
0  user1   B   C   D   E
1  user1  B1  C1  D1  E1
2  user2  B2  C2  D2  E2
3  user3  B3  C3  D3  E3
4  user2  B4  C4  D4  E4
5  user3  B5  C5  D5  E5

In [5]:
df1.groupby('User').apply(lambda df: df.sample(1))

User   B   C   D   E
User                          
user1 1  user1  B1  C1  D1  E1
user2 4  user2  B4  C4  D4  E4
user3 5  user3  B5  C5  D5  E5

In [2]:
a = ['dum'] * 3
b = ['2']
c = a+b
print(c)

['dum', 'dum', 'dum', '2']


In [3]:
for dummie_count in range(2):
    print(dummie_count)

0
1


In [5]:
df = pd.DataFrame({'A': [0, 1, 2, 3, 4],
...                    'B': [5, 6, 7, 8, 9],
...                    'C': ['a', 'b', 'c', 'd', 'e']})
df

A  B  C
0  0  5  a
1  1  6  b
2  2  7  c
3  3  8  d
4  4  9  e

In [24]:
a=[[-0.74062822, -1.23664232, -0.7927678 ],[-0.74, -1.23, -0.79],[-0.7, -1.2, -0.8]]
#b = a[np.argwhere(a==np.median(a,0)[0])[0][0]]
b = np.median(a,0)
b

array([-0.74     , -1.23     , -0.7927678])

In [19]:
df_results = pd.DataFrame( columns=[ 'target_variable'])


[-0.74, -1.23, -0.79]

In [7]:
liste = [1,23,4]
liste[2]

4