In [1]:
from sklearn.metrics import mean_squared_error, r2_score, explained_variance_score
import numpy as np

In [4]:
stri= 'bia_bla'
'bia' in stri
stri2 = stri.replace('_','')
stri
stri2

'biabla'

In [2]:
a = np.array([[0,2,3],[4,5,6]])
a[:,:2]

array([[0, 2],
       [4, 5]])

In [8]:
b = [0,2,3]
d = [0,2,3]

In [9]:
c = np.vstack((d,b))
c

array([[0, 2, 3],
       [0, 2, 3]])

In [16]:
b=np.median(a, axis=0)
a
b

array([2. , 3.5, 4.5])

In [15]:
a

array([[0, 2, 3],
       [4, 5, 6]])

In [18]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [2]:
a = [1,2,3,4,5]
a = [2 if x < 4 else x for x in a ]
b = [2 for x in a if x < 4]
b

[2, 2, 2]

In [6]:
a.append(2)
a

[2, 2, 2, 4, 5, 2, 2, 2]